### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by AntoineDuvalCodes** [Mangopay/cardregistration-android-kit#23]
Bonjours,
Le kit android marche parfaitement pour créer une nouvelle carte lorsque je l'utilise sans activer proguard (minifyEnabled false).
En revanche, lorsque je l'active (minifyEnabled true) le callback n'est jamais appelé (ni en success, ni en failure), je n'ai donc jamais de réponse de la part de votre méthode: mangopay.registerCard(mCard, Callback).

Avez vous un moyen de contourner ce problème ?

**Comment by tperraut-geronimo** [comment]
Même problème chez moi.

**Comment by Name-less** [comment]
Pareil ici, une idée ... ?

**Comment by tperraut-geronimo** [comment]
Personnellement j'ai ajouté la ligne suivante à proguard :
```
# Mangopay
-keep class com.mangopay.** { *; }
```
C'est le `minifyEnabled false` dans le sample qui m'a mis la puce à l'oreille.

**Comment by Name-less** [comment]
Oé j'ai essayé mais le callback n'est pas non plus appelé, faut croire que ce n'était pas (que) lié à proguard de mon côté ...

**Comment by mangomaxoasis** [comment]
Bonjour @Name-less  @AntoineDuvalCodes  @tperraut-geronimo 

En effet dans cette situation il y a un bug sur le callback, on revoit ce process de notre côté
 
La solution de @tperraut-geronimo est bonne, 
# Mangopay
-keep class com.mangopay.** { *; }

Vous pourriez aussi enlever Proguard -> la librairie MangoPay est publique de toute façon

**Comment by cesaramnuel** [comment]
As of December 2020, this issues is still open. We have added `-keep class com.mangopay.** { *; }` as specified, and it worked on emulators with API 30, but did not on physical devices. The problem still persists when trying to create a new card with `registerCard`. For some reason, callback function is not triggered. We have also set `minifyEnabled false`. Any advice?

**Comment by octa-george** [comment]
Hello @cesaramnuel . We have just released v. 1.0.2. Please check it out and let us know if you still encounter any other issues.

**Comment by cesaramnuel** [comment]
Hi @octa-george, we're unable to find the new release:

`Could not find com.mangopay.android.sdk:card-registration-library:1.0.2.`

**Comment by octa-george** [comment]
You can download the `.aar` file directly from [link](https://bintray.com/mangopay/cardregistration-android-kit/download_file?file_path=com%2Fmangopay%2Fandroid%2Fsdk%2Fcard-registration-library%2F1.0.2%2Fcard-registration-library-1.0.2.aar). 

After that simply put `implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')` or `implementation(name:'card-registration-library-1.0.2', ext:'aar')` or `implementation 'com.mangopay.android.sdk:card-registration-library:1.0.2@aar'` to your app/build.gradle `dependencies.

**Comment by octa-george** [comment]
Related to #28. Fixed in version 1.0.3
