### ISSUE TITLE
Issues with the card tokenisation ?

### ISSUE THREAD

**Issue by bogdanmunteanu** [Mangopay/cardregistration-android-kit#24]
I have implemented in my app payment with mangopay and I have an Android app that needs to use it .
On the backend I have implemented the CardRegistration which gives me the details for the tokenisation server on the mobile app . I call the tokenisation server and receive the card token , but when I pass it on to the backend , the payment fails. Any reason why this is happening ?

**Comment by mangomaxoasis** [comment]
Hi @bogdanmunteanu 
Is the error persisting?
Please contact us if need be
