### ISSUE TITLE
Callback never called

### ISSUE THREAD

**Issue by Name-less** [Mangopay/cardregistration-android-kit#25]
When I try to register a card with the SDK on the sandbox environnement, the callback is never called, even with a false card number.
I tried with every card registration method available, none of them works.

In your SDK, the flow is working until `getTokenSuccess` method which never callback the `serviceCallback`.

```
//on MangoPay.java
  private void getTokenSuccess(String response) {
 CardRegistrationInteractor.Callback serviceCallback = new CardRegistrationInteractor.Callback() {
      @Override public void onCardRegistrationSuccess(CardRegistration response) {
         //NEVER PASS HERE
        cardRegistrationSuccess(response);
      }

      @Override public void onCardRegistrationError(MangoException error) {
            //NEVER PASS HERE
          cardRegistrationError(error);
      }
    };
```

I will have to pass the card information to my backend even if this is not allowed, no choices ...

**Comment by catacraciun** [comment]
@Name-less if you have Proguard on your app, please have a look at issue #23 . This will be fixed on that ticket.

**Comment by mangomaxoasis** [comment]
Hey @Name-less,
Feel free to contact us, I am for the moment closing this issue.
Max
