### ISSUE TITLE
mangopay api is not working

### ISSUE THREAD

**Issue by Mfaisal541** [Mangopay/cardregistration-android-kit#26]
When i am creating a legal user on mangopay then mango pay is not working and  throw exception and user is not created  and  check this may code is exception 

and my error is this plz check and give me a solution
Warning: Creating default object from empty value in /home/leadconcept/public_html/clients/abrar/freelancer/wp-content/themes/superlist-child/vpb_create_mangopay.php on line 204

Warning: Creating default object from empty value in /home/leadconcept/public_html/clients/abrar/freelancer/wp-content/themes/superlist-child/vpb_create_mangopay.php on line 211
MangoPay\ResponseException Code: 404
-------------------------------
Message: Not found
-------------------------------
Details: 
-------------------------------

**Comment by mangomaxoasis** [comment]
Hi @Mfaisal541 
I think this error is better treated in the PHP SDK, there seems to be PHP custom code in this call.
We would need for info.
Best,
Max

**Comment by mangomaxoasis** [comment]
issue closed
