### ISSUE TITLE
Can't add the repo

### ISSUE THREAD

**Issue by benjaminledet** [Mangopay/cardregistration-android-kit#32]
Hello,
I can't add the dependency `com.mangopay.android.sdk:card-registration-library:1.0.3` in gradle, it doesn't find it. It worked with the version `1.0.1`.
And the link in the readme to download the aar is broken.

**Comment by fredericdelordm** [comment]
Hello @benjaminledet,

Let me double check this and come back to you

**Comment by benjaminledet** [comment]
Hi, any update on this?

**Comment by fredericdelordm** [comment]
Hello @benjaminledet,

An Android developer is looking at it. I'll keep you updated.

Sorry for the inconvenience,

**Comment by SorianoBenjamin** [comment]
Hello, for me it does not work with 1.0.1 and 1.0.3. Gradles found the both versions but in android studio I have "Cannot resolve symbol 'mangopay'". I restart the cache but I still have the problem

**Comment by PatelJa02** [comment]
Hello Any update on this issue?

**Comment by jidefela-mgp** [comment]
Hello @PatelJa02 

We deprecated this SDK on July 21, 2023 and it will no longer be maintained or supported.

You should upgrade to the newest version of our [Vault SDK](https://mangopay.com/docs/sdk/vault-android), and release a new version of your application. The new SDK provides the same functionality of [card registration flow](https://mangopay.com/docs/endpoints/direct-card-payins#card-registration-object), with Kotlin language support., better performance, and continued support.
