### ISSUE TITLE
Cannot cast ‘java.lang.Double’ to ‘java.lang.Long’ in JsonUtil.java  when the error.setTimestamp((Long) json.get("Date")) is executed

### ISSUE THREAD

**Issue by PatelJa02** [Mangopay/cardregistration-android-kit#36]
Hello,

Mangopay callback is not getting called when the same card tries to register again so I debugged the code of the mangopay sdk library and found the following:->                                                                                                                                   **MangoPay API Response**: {"Message":"the card registration has already been processed","Type":"cardregistration_already_process","Id":"191db6e2-5abc-4448-b255-2b2ac216c756#1648708963","Date":1648708964,"errors":null}

**MangoPay Card Registration SDK Code**: MangoException error = new MangoException(getValue(json, "Id"), getValue(json, "Message"), getValue(json, "Type"));
if (json.has("Date") && !json.isNull("Date")) {
  error.setTimestamp((Long) json.get("Date"));
}

Getting this exception "Cannot cast ‘java.lang.Double’ to ‘java.lang.Long’"  when the below code is executed 
**error.setTimestamp((Long) json.get("Date"));** in **JsonUtils.java file**                                                                                      So callback is not getting called due above issue 
Please fix this issue.

**Comment by catacraciun** [comment]
Hi @PatelJa02 . What Android version are you using? A fix will be pushed shortly anyway, but I'm just curious if it's happening only on newer Android versions or not.

**Comment by PatelJa02** [comment]
Hello @catacraciun 
Thanks for fixing it, I have produced the issues in the android 11 with the device Samsung A50.

**Comment by PatelJa02** [comment]
Hello @catacraciun, What  is the expected time in we receive the above fixes SDK version

**Comment by jidefela-mgp** [comment]
Hello @PatelJa02 

Please consider upgrading to our new [Vault SDK](https://mangopay.com/docs/sdk/vault-android), thanks
