### ISSUE TITLE
Callback for "SecureMode" :"FORCE"

### ISSUE THREAD

**Issue by MehulKK** [Mangopay/cardregistration-android-kit#39]
I have implemented card registration using secure mode. When get registration get success it will return SecureModeRedirectURL that will open in Custom chrome tab browser for validation. Once validation get success then it will not redirect back to application.  

Thanks in advance

**Comment by jidefela-mgp** [comment]
Hello @MehulKK, apologies for the delay.

It seems to be that what you are referring to is one of our PayIn APIs (which is not part of this SDK), as we do not have `SecureMode` flag/behaviour in our card registration flow. Could you please confirm which SDK you have used in your implementation?

**Comment by jidefela-mgp** [comment]
Hello @MehulKK 

We deprecated this SDK on July 21, 2023 and it will no longer be maintained or supported.

You should upgrade to the newest version of our [Vault SDK](https://mangopay.com/docs/sdk/vault-android), and release a new version of your application. The new SDK provides the same functionality of [card registration flow](https://mangopay.com/docs/endpoints/direct-card-payins#card-registration-object), with Kotlin language support., better performance, and continued support.

thanks!
